name: conrft2
channels:
  - defaults
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - alsa-lib=1.2.15.1=hb03c661_0
  - attr=2.5.2=h39aace5_0
  - binutils=2.45=default_h4852527_105
  - binutils_impl_linux-64=2.45=default_hfdba357_105
  - binutils_linux-64=2.45=default_h4852527_105
  - bzip2=1.0.8=h5eee18b_6
  - c-compiler=1.7.0=hd590300_1
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cairo=1.18.0=h3faef2a_0
  - cuda-cccl=12.1.109=ha770c72_0
  - cuda-cccl-impl=2.0.1=ha770c72_1
  - cuda-cccl_linux-64=12.1.109=ha770c72_0
  - cuda-command-line-tools=12.1.1=ha770c72_0
  - cuda-compiler=12.1.1=hbad6d8a_0
  - cuda-cudart=12.1.105=hd3aeb46_0
  - cuda-cudart-dev=12.1.105=hd3aeb46_0
  - cuda-cudart-dev_linux-64=12.1.105=h59595ed_0
  - cuda-cudart-static=12.1.105=hd3aeb46_0
  - cuda-cudart-static_linux-64=12.1.105=h59595ed_0
  - cuda-cudart_linux-64=12.1.105=h59595ed_0
  - cuda-cuobjdump=12.1.111=h59595ed_0
  - cuda-cupti=12.1.105=h59595ed_0
  - cuda-cupti-dev=12.1.105=h59595ed_0
  - cuda-cuxxfilt=12.1.105=h59595ed_0
  - cuda-driver-dev=12.1.105=hd3aeb46_0
  - cuda-driver-dev_linux-64=12.1.105=h59595ed_0
  - cuda-gdb=12.1.105=hd47b8d6_0
  - cuda-libraries=12.1.1=ha770c72_0
  - cuda-libraries-dev=12.1.1=ha770c72_0
  - cuda-nsight=12.1.105=ha770c72_0
  - cuda-nvcc=12.1.105=hcdd1206_1
  - cuda-nvcc-dev_linux-64=12.1.105=ha770c72_0
  - cuda-nvcc-impl=12.1.105=hd3aeb46_0
  - cuda-nvcc-tools=12.1.105=hd3aeb46_0
  - cuda-nvcc_linux-64=12.1.105=h8a487aa_1
  - cuda-nvdisasm=12.1.105=h59595ed_0
  - cuda-nvml-dev=12.1.105=h59595ed_0
  - cuda-nvprof=12.1.105=h59595ed_0
  - cuda-nvprune=12.1.105=h59595ed_0
  - cuda-nvrtc=12.1.105=hd3aeb46_0
  - cuda-nvrtc-dev=12.1.105=hd3aeb46_0
  - cuda-nvtx=12.1.105=h59595ed_0
  - cuda-nvvp=12.1.105=h59595ed_0
  - cuda-opencl=12.1.105=h59595ed_0
  - cuda-opencl-dev=12.1.105=h59595ed_0
  - cuda-profiler-api=12.1.105=ha770c72_0
  - cuda-sanitizer-api=12.1.105=h59595ed_0
  - cuda-toolkit=12.1.1=ha804496_0
  - cuda-tools=12.1.1=ha770c72_0
  - cuda-version=12.1=h1d6eff3_3
  - cuda-visual-tools=12.1.1=ha770c72_0
  - cxx-compiler=1.7.0=h00ab1b0_1
  - dbus=1.13.6=h5008d03_3
  - evdev=1.9.2=py310h7c4b9e2_1
  - expat=2.7.3=h7354ed3_4
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - freetype=2.14.1=ha770c72_0
  - gcc=12.4.0=h236703b_2
  - gcc_impl_linux-64=12.4.0=h26ba24d_2
  - gcc_linux-64=12.4.0=h6b7512a_10
  - gds-tools=1.6.1.9=hd3aeb46_0
  - glib=2.84.0=h07242d1_0
  - glib-tools=2.84.0=h4833e2c_0
  - gmp=6.3.0=hac33072_2
  - graphite2=1.3.14=hecca717_2
  - gst-plugins-base=1.24.4=h9ad1361_0
  - gstreamer=1.24.4=haf2f30d_0
  - gxx=12.4.0=h236703b_2
  - gxx_impl_linux-64=12.4.0=h3ff227c_2
  - gxx_linux-64=12.4.0=h8489865_10
  - harfbuzz=9.0.0=hfac3d4d_0
  - icu=73.2=h59595ed_0
  - kernel-headers_linux-64=5.14.0=he073ed8_3
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h166bdaf_1003
  - ld_impl_linux-64=2.45=default_hbd61a6d_105
  - libcap=2.77=h3ff7636_0
  - libclang-cpp15=15.0.7=default_h127d8a8_5
  - libclang13=19.1.2=default_h9c6a7e4_1
  - libcublas=12.1.3.1=hd3aeb46_0
  - libcublas-dev=12.1.3.1=hd3aeb46_0
  - libcufft=11.0.2.54=hd3aeb46_0
  - libcufft-dev=11.0.2.54=hd3aeb46_0
  - libcufile=1.6.1.9=hd3aeb46_0
  - libcufile-dev=1.6.1.9=hd3aeb46_0
  - libcups=2.3.3=hb8b1518_5
  - libcurand=10.3.2.106=hd3aeb46_0
  - libcurand-dev=10.3.2.106=hd3aeb46_0
  - libcusolver=11.4.5.107=hd3aeb46_0
  - libcusolver-dev=11.4.5.107=hd3aeb46_0
  - libcusparse=12.1.0.106=hd3aeb46_0
  - libcusparse-dev=12.1.0.106=hd3aeb46_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.7.3=h7354ed3_4
  - libffi=3.4.4=h6a678d5_1
  - libflac=1.5.0=he200343_1
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=h69a1729_7
  - libgcc-devel_linux-64=12.4.0=h1762d19_102
  - libgcc-ng=15.2.0=h166f726_7
  - libglib=2.84.0=h2ff4ddf_0
  - libgomp=15.2.0=h4751f2c_7
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.2=hb03c661_0
  - libllvm15=15.0.7=hb3ce162_4
  - libllvm19=19.1.2=ha7bfdaf_0
  - libnpp=12.1.0.40=hd3aeb46_0
  - libnpp-dev=12.1.0.40=hd3aeb46_0
  - libnsl=2.0.0=h5eee18b_0
  - libnuma=2.0.18=hb9d3cd8_3
  - libnvjitlink=12.1.105=hd3aeb46_0
  - libnvjitlink-dev=12.1.105=hd3aeb46_0
  - libnvjpeg=12.2.0.2=h59595ed_0
  - libnvjpeg-dev=12.2.0.2=ha770c72_0
  - libogg=1.3.5=hd0c01bc_1
  - libopus=1.6=h0fd0de7_0
  - libpng=1.6.53=h421ea60_0
  - libpq=16.11=hc183893_2
  - libsanitizer=12.4.0=ha732cd4_2
  - libsndfile=1.2.2=hc7d488a_2
  - libsqlite=3.51.1=h0c1763c_1
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-devel_linux-64=12.4.0=h1762d19_102
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libsystemd0=258.3=h6569c3e_0
  - libuuid=2.41.3=h5347b49_0
  - libvorbis=1.3.7=h54a6638_2
  - libxcb=1.15=h0b41bf4_0
  - libxkbcommon=1.7.0=h662e7e4_0
  - libxkbfile=1.1.0=h166bdaf_1
  - libxml2=2.12.7=h4c95cb1_3
  - libzlib=1.3.1=hb25bd0a_0
  - mpg123=1.32.9=hc50e24c_0
  - mysql-common=8.3.0=h70512c7_5
  - mysql-libs=8.3.0=ha479ceb_5
  - ncurses=6.5=h7934f7d_0
  - nsight-compute=2023.1.1.4=h3718151_0
  - nspr=4.38=h29cc59b_0
  - nss=3.118=h445c969_0
  - ocl-icd=2.3.3=hb9d3cd8_0
  - opencl-headers=2025.06.13=h5888daf_0
  - openssl=3.6.0=h26f9b46_0
  - packaging=25.0=pyh29332c3_1
  - pcre2=10.44=hc749103_2
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h54a6638_1
  - pthread-stubs=0.3=h0ce48e5_1
  - pulseaudio-client=17.0=hb77b528_0
  - pynput=1.8.1=py310hff52083_1
  - python=3.10.12=hd12c33a_0_cpython
  - python-xlib=0.33=pyhff2d567_1
  - python_abi=3.10=8_cp310
  - qt-main=5.15.8=hc9dc06e_21
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py310h06a4308_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.51.1=he0a8d7e_0
  - sysroot_linux-64=2.34=h087de78_3
  - tk=8.6.13=noxft_hd72426e_102
  - tzdata=2025b=h04d1e81_0
  - wayland=1.23.1=h3e06ad9_0
  - wheel=0.45.1=py310h06a4308_0
  - xcb-util=0.4.0=hd590300_1
  - xcb-util-image=0.4.0=h8ee46fc_1
  - xcb-util-keysyms=0.4.0=h8ee46fc_1
  - xcb-util-renderutil=0.3.9=hd590300_1
  - xcb-util-wm=0.4.1=h8ee46fc_1
  - xkeyboard-config=2.42=h4ab18f5_0
  - xorg-compositeproto=0.4.2=hb9d3cd8_1002
  - xorg-damageproto=1.2.1=hb9d3cd8_1003
  - xorg-fixesproto=5.0=hb9d3cd8_1003
  - xorg-inputproto=2.3.2=hb9d3cd8_1003
  - xorg-kbproto=1.0.7=hb9d3cd8_1003
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.9=h8ee46fc_0
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxcomposite=0.4.6=h0b41bf4_1
  - xorg-libxdamage=1.1.5=h7f98852_1
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxi=1.7.10=h4bc722e_1
  - xorg-libxrandr=1.5.2=h7f98852_1
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-libxtst=1.2.5=h4bc722e_0
  - xorg-randrproto=1.5.0=hb9d3cd8_1002
  - xorg-recordproto=1.14.2=hb9d3cd8_1003
  - xorg-renderproto=0.11.1=hb9d3cd8_1003
  - xorg-util-macros=1.20.2=hb9d3cd8_0
  - xorg-xextproto=7.3.0=hb9d3cd8_1004
  - xorg-xf86vidmodeproto=2.3.1=hb9d3cd8_1005
  - xorg-xorgproto=2025.1=hb03c661_0
  - xorg-xproto=7.0.31=hb9d3cd8_1008
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - absl-py==2.3.1
      - agentlace==0.1.3
      - aiofiles==25.1.0
      - array-record==0.8.1
      - asttokens==3.0.1
      - astunparse==1.6.3
      - attrs==25.4.0
      - cachetools==6.2.4
      - certifi==2026.1.4
      - cffi==2.0.0
      - cfgv==3.5.0
      - charset-normalizer==3.4.4
      - chex==0.1.85
      - click==8.3.1
      - cloudpickle==3.1.2
      - cmeel==0.57.3
      - cmeel-assimp==5.4.3.1
      - cmeel-boost==1.82.0
      - cmeel-console-bridge==1.0.2.3
      - cmeel-octomap==1.10.0
      - cmeel-tinyxml==2.6.2.3
      - cmeel-urdfdom==3.1.1.1
      - cmeel-zlib==1.3.1
      - contextlib2==21.6.0
      - contourpy==1.3.2
      - cycler==0.12.1
      - daqp==0.7.2
      - decorator==4.4.2
      - distlib==0.4.0
      - distrax==0.1.5
      - dlimp==0.0.1
      - dm-env==1.6
      - dm-robotics-transformations==0.10.0
      - dm-tree==0.1.9
      - docker-pycreds==0.4.0
      - docstring-parser==0.17.0
      - easyhid==0.0.10
      - eigenpy==3.1.3
      - einops==0.6.1
      - encoder-sdk==1.1.0
      - etils==1.13.0
      - exceptiongroup==1.3.1
      - executing==2.2.1
      - farama-notifications==0.0.4
      - filelock==3.20.2
      - flatbuffers==25.12.19
      - flax==0.10.2
      - flexiv-interface==0.1.0
      - flexivrdk==1.7.0
      - fonttools==4.61.1
      - franka-sim==0.0.1
      - fsspec==2025.12.0
      - gast==0.7.0
      - gitdb==4.0.12
      - gitpython==3.1.46
      - glfw==2.10.0
      - google-auth==2.41.1
      - google-auth-oauthlib==1.2.3
      - google-pasta==0.2.0
      - grpcio==1.76.0
      - gym==0.26.2
      - gym-notices==0.1.0
      - gymnasium==0.29.1
      - h5py==3.15.1
      - hf-xet==1.2.0
      - hidapi==0.15.0
      - hpp-fcl==2.3.6
      - huggingface-hub==0.36.0
      - humanize==4.15.0
      - identify==2.6.15
      - idna==3.11
      - imageio==2.31.1
      - imageio-ffmpeg==0.6.0
      - immutabledict==4.2.2
      - importlib-resources==6.5.2
      - ipython==8.38.0
      - jax==0.6.2
      - jax-cuda12-pjrt==0.6.2
      - jax-cuda12-plugin==0.6.2
      - jaxlib==0.6.2
      - jedi==0.19.2
      - jinja2==3.1.6
      - keras==2.15.0
      - kiwisolver==1.4.9
      - libclang==18.1.1
      - loguru==0.7.3
      - loop-rate-limiters==1.2.0
      - lxml==6.0.2
      - lz4==4.4.5
      - markdown==3.10
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - matplotlib-inline==0.2.1
      - mdurl==0.1.2
      - minimalmodbus==2.1.1
      - ml-collections==0.1.0
      - ml-dtypes==0.5.0
      - moviepy==1.0.3
      - mpmath==1.3.0
      - msgpack==1.1.2
      - mujoco==2.3.7
      - namex==0.1.0
      - narwhals==2.15.0
      - natsort==8.4.0
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - nodeenv==1.10.0
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.9.1.4
      - nvidia-cuda-cccl-cu12==12.9.27
      - nvidia-cuda-cupti-cu12==12.9.79
      - nvidia-cuda-nvcc-cu12==12.9.86
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.9.79
      - nvidia-cudnn-cu12==9.17.1.4
      - nvidia-cufft-cu12==11.4.1.4
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.7.5.82
      - nvidia-cusparse-cu12==12.5.10.65
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvshmem-cu12==3.5.19
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.3.1
      - octo==0.0.0
      - opencv-python==4.12.0.88
      - opt-einsum==3.4.0
      - optax==0.1.5
      - optree==0.18.0
      - orbax-checkpoint==0.4.4
      - parso==0.8.5
      - pathlib==1.0.1
      - pathtools==0.1.2
      - pexpect==4.9.0
      - pillow==12.1.0
      - pin==2.6.20
      - pin-pink==3.5.0
      - platformdirs==4.5.1
      - plotly==6.5.2
      - pre-commit==3.3.3
      - proglog==0.1.12
      - promise==2.3
      - prompt-toolkit==3.0.52
      - protobuf==3.20.0
      - psutil==7.2.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==22.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pybind11==3.0.1
      - pycparser==2.23
      - pygments==2.19.2
      - pyopengl==3.1.10
      - pyorbbecsdk2==2.0.15
      - pyparsing==3.3.1
      - pyquaternion==0.9.9
      - pyrealsense2==2.54.2.5684
      - pyrobotiqgripper==1.0.1
      - pyserial==3.5
      - pyspacemouse==1.1.5
      - python-dateutil==2.9.0.post0
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - qpsolvers==4.8.2
      - regex==2026.1.15
      - requests==2.32.5
      - requests-oauthlib==2.0.0
      - rich==14.2.0
      - rsa==4.9.1
      - safetensors==0.7.0
      - scipy==1.15.3
      - sentry-sdk==2.48.0
      - serl-launcher==0.1.2
      - setproctitle==1.3.7
      - shortuuid==1.0.13
      - simple-parsing==0.1.7
      - simplejson==3.20.2
      - smmap==5.0.2
      - spdlog==2.0.6
      - stack-data==0.6.3
      - sympy==1.14.0
      - tensorboard==2.15.2
      - tensorboard-data-server==0.7.2
      - tensorflow==2.15.0
      - tensorflow-datasets==4.9.9
      - tensorflow-estimator==2.15.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - tensorflow-metadata==1.17.3
      - tensorflow-probability==0.23.0
      - tensorstore==0.1.78
      - termcolor==3.3.0
      - tf-keras==2.15.0
      - tokenizers==0.22.2
      - toml==0.10.2
      - tomli==2.3.0
      - toolz==1.1.0
      - torch==2.3.0
      - torchaudio==2.3.0
      - torchvision==0.18.0
      - tqdm==4.60.0
      - traitlets==5.14.3
      - transformers==4.57.5
      - treescope==0.1.10
      - triton==2.3.0
      - typing==3.7.4.3
      - typing-extensions==4.15.0
      - urllib3==2.6.2
      - virtualenv==20.35.4
      - wandb==0.12.14
      - wcwidth==0.2.14
      - werkzeug==3.1.4
      - wrapt==1.14.2
      - zipp==3.23.0
      - zmq==0.0.0
prefix: /home/dx/miniconda3/envs/conrft2
